
export enum LoadingStates {
    SAVE = 'SAVE',
    ACTIVATE_DEACTIVATE = 'ACTIVATE_DEACTIVATE'
}

export enum TemplateCreationSteps {
    TEMPLATE_FORM = 'TEMPLATE_FORM',
    TEMPLATE_BUILDER = 'TEMPLATE_BUILDER',
    EXPORT_LAYOUT = 'EXPORT_LAYOUT',
}